<?php

namespace TomatoPHP\FilamentInvoices\Filament\Resources\InvoiceResource\Pages;

use Filament\Resources\Pages\CreateRecord;
use TomatoPHP\FilamentInvoices\Filament\Resources\InvoiceResource;

class CreateInvoice extends CreateRecord
{
    protected static string $resource = InvoiceResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['user_id'] = auth()->id();

        return $data; // TODO: Change the autogenerated stub
    }

    public function afterCreate()
    {
        $data = [];
        $data['discount'] = collect($this->getRecord()->invoicesItems)->sum(function ($item) {
            return $item->discount * $item->qty;
        });
        $data['vat'] = collect($this->getRecord()->invoicesItems)->sum(function ($item) {
            return $item->vat * $item->qty;
        });
        $data['total'] = collect($this->getRecord()->invoicesItems)->sum('total');

        $this->getRecord()->update($data);

        $this->getRecord()->invoiceLogs()->create([
            'log' => 'Invoice created By: ' . auth()->user()->name,
            'type' => 'created',
        ]);
    }
}
